### ISSUE TITLE
Still: Deep copy breaks on instances of EventEmitter in node versions 6.0.0 and onward

### ISSUE THREAD

**Issue by nodesocket** [mrluc/owl-deepcopy#6]
Doing some trial and error, adding two more guards seems to fix it completely.

The guards are adding `source.hasOwnProperty`

```javascript
// Generic Object copier
// the ultimate fallback DeepCopier, which tries to handle the generic case.  This
// should work for base Objects and many user-defined classes.
deepCopy.register({
  canCopy: function(source) { return true; },
  
  create: function(source) {
    if ( source.hasOwnProperty && source instanceof source.constructor ) {
      return clone(source.constructor.prototype);
    } else {
      return {};
    }
  },
  
  populate: function(deepCopy, source, result) {
    for ( var key in source ) {
      if ( source.hasOwnProperty && source.hasOwnProperty(key) ) {
	result[key] = deepCopy(source[key]);
      }
    }
    return result;
  }
});
```

Does that seem right?

**Comment by nodesocket** [comment]
@acusti for reference.

**Comment by acusti** [comment]
Maybe worth mentioning that the extra guards are there because we were continuing to get:

```
node_modules/owl-deepcopy/deep_copy.js:228
    if ( source instanceof source.constructor ) {
                                 ^

TypeError: Expecting a function in instanceof check, but got undefined
```

And when we added a guard to that check to avoid calling instanceof when `source.constructor` is undefined, it would then create an error with `source.hasOwnProperty` not being defined. This is happening to us when deepcopy is invoked from [mongoose-schema-extend](https://github.com/briankircho/mongoose-schema-extend) on certain parts of our schemas. The objects on which it breaks have no `constructor` or `__proto__` properties; they may be EventEmitter objects, but in that case, #5 isn’t working, because the generic object copier is getting invoked for them (that’s where the error happens).

**Comment by mrluc** [comment]
Ah -- good guards, y'all. Published 0.0.6.

**Comment by mrluc** [comment]
@acusti lmk if that works for you and I'll close this

**Comment by nodesocket** [comment]
0.0.6 worked. Thanks so much!
